//go:build e2e

package cli_test

import (
	"os/exec"
	"strings"
	"testing"
)

// TestCLIRoots verifies `goclaw --help` lists exactly the kept root commands
// and none of the dropped ones. The kept set:
//
//	gateway (root run; no subcommand)
//	version, doctor, migrate, upgrade, backup, restore, reset-password
//
// `completion` and `help` are auto-generated by cobra and tolerated.
func TestCLIRoots(t *testing.T) {
	out, err := exec.Command(goclawBin, "--help").CombinedOutput()
	if err != nil {
		t.Fatalf("goclaw --help: %v\n%s", err, out)
	}

	verbs := parseAvailableCommandVerbs(string(out))
	if len(verbs) == 0 {
		t.Fatalf("could not locate Available Commands block in:\n%s", out)
	}

	got := map[string]bool{}
	for _, v := range verbs {
		got[v] = true
	}

	mustContain := []string{
		"version", "doctor", "migrate", "upgrade",
		"backup", "restore", "reset-password",
	}
	for _, cmd := range mustContain {
		if !got[cmd] {
			t.Errorf("missing kept command %q. Available: %v", cmd, verbs)
		}
	}

	mustNotContain := []string{
		"onboard", "auth", "agent", "agent-chat",
		"channels", "config", "cron", "pairing",
		"providers", "sessions", "skills", "prompt",
		"setup", "tui", "tenant-backup", "tenant-restore",
	}
	for _, cmd := range mustNotContain {
		if got[cmd] {
			t.Errorf("dropped command %q still registered. Available: %v", cmd, verbs)
		}
	}
}

// parseAvailableCommandVerbs returns the first token of each line in the
// "Available Commands:" block of cobra's --help output.
func parseAvailableCommandVerbs(help string) []string {
	const marker = "Available Commands:"
	idx := strings.Index(help, marker)
	if idx < 0 {
		return nil
	}
	rest := help[idx+len(marker):]

	var verbs []string
	for _, line := range strings.Split(rest, "\n") {
		// Block ends at the first blank line.
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			if len(verbs) > 0 {
				break
			}
			continue
		}
		// Lines are indented; verb is the first whitespace-separated token.
		fields := strings.Fields(trimmed)
		if len(fields) == 0 {
			continue
		}
		verbs = append(verbs, fields[0])
	}
	return verbs
}
